### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by bigboy-baby** [Shubhgajj2004/Stable-diffusion-free-API#1]
Guess the api died? I get 404 not found every time.

**Comment by bigboy-baby** [comment]
Great

**Comment by bigboy-baby** [comment]
Yo my fault bro the new one still is 404. I didn't check ig

**Comment by bigboy-baby** [comment]
> @bigboy-baby Use this one I updated the url. Now check once again it will work. Thank you for raising an issue

It's still broken

**Comment by Shubhgajj2004** [comment]
@bigboy-baby which part is not working? Prompt suggestion or Image generation?

**Comment by Shubhgajj2004** [comment]
@bigboy-baby Now I have changed again. And it is working. Check it out

**Comment by bigboy-baby** [comment]
> @bigboy-baby Now I have changed again. And it is working. Check it out

Works, thanks. Why did it stop working, twice, btw? Credits issue or?
