### ISSUE TITLE
Hello BRO BIG THANKS FOR THIS GITHUB!!!! can I add other models??? it is possible??

### ISSUE THREAD

**Issue by Juranik** [Shubhgajj2004/Stable-diffusion-free-API#2]
BRO BIG THANKS! If I want add other models, for example SDXL? Can I add models from Civitai? Or from huggingface? it is possible?

**Comment by Shubhgajj2004** [comment]
You can actually add them all if they are accessible via the API. Otherwise, there are two options: you can either run it on your local computer or host it on servers (which can be very costly).
